In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
dat1 = pd.read_csv("3rd_ppp_for_upload_win.csv", encoding = "ISO-8859-1")
dat2 = pd.read_csv("atm_for_upload_win.csv", encoding = "ISO-8859-1")
dat3 = pd.read_csv("banks_for_upload_win.csv", encoding = "ISO-8859-1")
dat4 = pd.read_csv("bus_stands_for_upload_win.csv", encoding = "ISO-8859-1")
dat5 = pd.read_csv("microfinance_for_upload_win.csv", encoding = "ISO-8859-1")
dat6 = pd.read_csv("mobilemoney_agents_for_upload_win.csv", encoding = "ISO-8859-1")
dat7 = pd.read_csv("pos_for_upload_win.csv", encoding = "ISO-8859-1")
dat8 = pd.read_csv("post_office_for_upload_win.csv", encoding = "ISO-8859-1")
dat9 = pd.read_csv("sacco_for_upload_win.csv", encoding = "ISO-8859-1")


c:\users\olaleye eniola\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (26,32,33,42,74) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
dat1 = dat1[['region', 'district', 'ward', 'latitude', 'longitude']]
dat2 = dat2[['region', 'district', 'ward', 'latitude', 'longitude']]
dat3 = dat3[['region', 'district', 'ward', 'latitude', 'longitude']]
dat4 = dat4[['region', 'district', 'ward', 'latitude', 'longitude']]
dat5 = dat5[['region', 'district', 'ward', 'latitude', 'longitude']]
dat6 = dat6[['region', 'district', 'ward', 'latitude', 'longitude']]
dat7 = dat7[['region', 'district', 'ward', 'latitude', 'longitude']]
dat8 = dat8[['region', 'district', 'ward', 'latitude', 'longitude']]
dat9 = dat9[['region', 'district', 'ward', 'latitude', 'longitude']]

In [4]:
data = pd.concat([dat1,dat2,dat3,dat4,dat5,dat6,dat7,dat8,dat9])

In [5]:
data.to_csv("all.csv",index = False)

In [6]:
data.head()

region   district         ward  latitude  longitude
0         Mwanza       Magu     Nyanguge  -2.36921   33.57654
1         Mwanza    Ilemela      Nyakato  -2.53201   32.94780
2  Dar es Salaam      Ilala      Segerea  -6.84188   39.21102
3  Dar es Salaam  Kinondoni  Kijitonyama  -6.77949   39.24092
4  Dar es Salaam     Temeke    Kigamboni  -6.82792   39.31021

In [7]:
data.isnull().sum()

region       20
district     19
ward         19
latitude      0
longitude     0
dtype: int64

In [8]:
data.dropna(inplace = True)

In [9]:
data.reset_index(inplace = True)

In [10]:
data.drop("index", axis = 1 ,inplace = True)

In [11]:
data.head()

region   district         ward  latitude  longitude
0         Mwanza       Magu     Nyanguge  -2.36921   33.57654
1         Mwanza    Ilemela      Nyakato  -2.53201   32.94780
2  Dar es Salaam      Ilala      Segerea  -6.84188   39.21102
3  Dar es Salaam  Kinondoni  Kijitonyama  -6.77949   39.24092
4  Dar es Salaam     Temeke    Kigamboni  -6.82792   39.31021

In [12]:
dataOriginal = data.copy()

In [13]:
data['district'] = data['district'].astype('category')


In [14]:
-4.46044192,29.8113964


(-4.46044192, 29.8113964)

In [15]:
data.nunique()

region          22
district       124
ward          1383
latitude     40399
longitude    41000
dtype: int64

In [16]:
#data['district'] = data['district'].astype('category')

data.drop_duplicates(inplace =True)
data.reset_index(inplace = True)
data.drop("index", axis = 1 ,inplace = True)

In [17]:
data.head()

region   district         ward  latitude  longitude
0         Mwanza       Magu     Nyanguge  -2.36921   33.57654
1         Mwanza    Ilemela      Nyakato  -2.53201   32.94780
2  Dar es Salaam      Ilala      Segerea  -6.84188   39.21102
3  Dar es Salaam  Kinondoni  Kijitonyama  -6.77949   39.24092
4  Dar es Salaam     Temeke    Kigamboni  -6.82792   39.31021

In [18]:
data[data["latitude"] == -2.36921]

region district      ward  latitude  longitude
0  Mwanza     Magu  Nyanguge  -2.36921   33.57654

In [19]:
X.head()

NameError: name 'X' is not defined

In [ ]:
data.dtypes

In [20]:

cat_columns = data.select_dtypes(['category']).columns

cat_columns
data[cat_columns] = data[cat_columns].apply(lambda x: x.cat.codes)
data.head()

region  district         ward  latitude  longitude
0         Mwanza        53     Nyanguge  -2.36921   33.57654
1         Mwanza        21      Nyakato  -2.53201   32.94780
2  Dar es Salaam        19      Segerea  -6.84188   39.21102
3  Dar es Salaam        38  Kijitonyama  -6.77949   39.24092
4  Dar es Salaam       118    Kigamboni  -6.82792   39.31021

In [21]:
data.district.nunique()

124

In [22]:
X= data.drop(["district","region","ward"], axis =1)
y = data["district"]

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=42)

In [24]:
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

c:\users\olaleye eniola\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [25]:
model = LogisticRegression()
rf = RandomForestClassifier()
xgb = XGBClassifier()

In [26]:
y_train.head()

49627    70
39556    25
11248    63
27827    38
10709    67
Name: district, dtype: int8

In [144]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [136]:
model.predict(X_test)

array([92, 38, 92, ..., 38, 25, 92], dtype=int8)

In [137]:
from sklearn.metrics import accuracy_score

In [145]:
accuracy_score(xgb.predict(X_test),y_test)

0.9362806515124396

In [142]:
accuracy_score(rf.predict(X_test),y_test)

0.9331185490125887

In [27]:
xgb.fit(X,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [28]:
dataOriginal.head()
#data[data["district"]==53]

region   district         ward  latitude  longitude
0         Mwanza       Magu     Nyanguge  -2.36921   33.57654
1         Mwanza    Ilemela      Nyakato  -2.53201   32.94780
2  Dar es Salaam      Ilala      Segerea  -6.84188   39.21102
3  Dar es Salaam  Kinondoni  Kijitonyama  -6.77949   39.24092
4  Dar es Salaam     Temeke    Kigamboni  -6.82792   39.31021

In [30]:




dataOriginal['ward'] = dataOriginal['ward'].astype('category')

dataOriginal.drop_duplicates(inplace =True)
dataOriginal.reset_index(inplace = True)
dataOriginal.drop("index", axis = 1 ,inplace = True)
dist = dataOriginal["ward"]
cat_columns = dataOriginal.select_dtypes(['category']).columns

cat_columns
dataOriginal[cat_columns] = dataOriginal[cat_columns].apply(lambda x: x.cat.codes)
dataOriginal.head()

region   district  ward  latitude  longitude
0         Mwanza       Magu  1131  -2.36921   33.57654
1         Mwanza    Ilemela  1110  -2.53201   32.94780
2  Dar es Salaam      Ilala  1228  -6.84188   39.21102
3  Dar es Salaam  Kinondoni   451  -6.77949   39.24092
4  Dar es Salaam     Temeke   433  -6.82792   39.31021

In [31]:
worked_out = pd.concat([dataOriginal["ward"],dist],axis =1)

In [32]:
worked_out.head()

ward         ward
0  1131     Nyanguge
1  1110      Nyakato
2  1228      Segerea
3   451  Kijitonyama
4   433    Kigamboni

In [33]:
worked_out.columns = ["ward",'main']

In [34]:
train = pd.read_csv("training.csv")

In [35]:
test = pd.read_csv("test.csv")

In [36]:
train.head()

ID  Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8_1  Q8_2             ...               \
0  5086  98   2   3   1   1   2   2     0     0             ...                
1  1258  40   1   1   3   5   1   1     1     0             ...                
2   331  18   2   4   6   3   2   1     0     0             ...                
3  6729  50   1   1   3   1   1   1     0     0             ...                
4  8671  34   1   1   1   1   2   1     0     1             ...                

   Q17  Q18  Q19  Latitude  Longitude  mobile_money  savings  borrowing  \
0   -1    4    4 -4.460442  29.811396             0        0          0   
1    4    1    4 -6.176438  39.244871             1        1          1   
2   -1    1    1 -6.825702  37.652798             1        0          0   
3   -1    1    4 -3.372049  35.808307             1        0          1   
4   -1    1    4 -7.179645  31.039095             1        1          0   

   insurance  mobile_money_classification  
0          0                            0  
1          0                            3  
2          0                            2  
3          0                            3  
4          1                            3  

[5 rows x 37 columns]

In [37]:
train = train[['Latitude','Longitude']]
test = test[['Latitude','Longitude']]
train.columns = ['latitude', 'longitude']
test.columns  = ['latitude', 'longitude']

In [38]:
train.head()

latitude  longitude
0 -4.460442  29.811396
1 -6.176438  39.244871
2 -6.825702  37.652798
3 -3.372049  35.808307
4 -7.179645  31.039095

In [39]:
test.head()

latitude  longitude
0 -2.596421  32.913584
1 -1.778303  34.062640
2 -1.851789  31.536866
3 -1.235656  34.229012
4 -7.780934  35.691878

In [40]:
train_destrict = xgb.predict(train)

c:\users\olaleye eniola\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [41]:
test_destrict = xgb.predict(test)

c:\users\olaleye eniola\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [42]:
#pd.DataFrame(train_destrict)

In [43]:
#dataOriginal.head()

In [44]:
#dataOriginal.reset_index(inplace=True)
#data.drop_duplicates(inplace= True)
#dataOriginal.drop("index",inplace=True)
#data.head()

In [45]:
worked_out.head()

ward         main
0  1131     Nyanguge
1  1110      Nyakato
2  1228      Segerea
3   451  Kijitonyama
4   433    Kigamboni

In [46]:
dick = dict(zip(worked_out.ward, worked_out.main))
dick

{1131: 'Nyanguge',
 1110: 'Nyakato',
 1228: 'Segerea',
 451: 'Kijitonyama',
 433: 'Kigamboni',
 947: 'Mtoni',
 1173: 'Pugu',
 742: 'Manzese',
 1321: 'Ukonga',
 550: 'Kitunda',
 1231: 'Sekei',
 675: 'Magomeni',
 648: 'Mabibo',
 1143: 'Nzega Mjini',
 1288: 'Tandika',
 1282: 'Tabata',
 761: 'Masoko',
 400: 'Keko',
 1035: 'Nambambo',
 1055: 'Ndoro',
 997: 'Mwananyamala',
 1287: 'Tandale',
 788: 'Mbagala',
 184: 'Gongoni',
 267: 'Ipembe',
 410: 'Kibamba',
 797: 'Mbezi',
 555: 'Kivukoni',
 436: 'Kigogo',
 1378: 'Yombo Vituka',
 537: 'Kisutu',
 365: 'Kariakoo',
 1366: 'Vingunguti',
 3: 'Azimio',
 39: 'Buguruni',
 653: 'Machame Magharibi',
 687: 'Majengo',
 673: 'Magole',
 396: 'Kawe',
 1302: 'Toangoma',
 479: 'Kimara',
 1186: 'Ruaha',
 1148: 'Olboloti',
 107: 'Chanika',
 142: 'Daraja Mbili',
 1160: 'Pamba',
 801: 'Mbugani',
 358: 'Kanyenye',
 557: 'Kiwalani',
 386: 'Kati',
 250: 'Ilala',
 1294: 'Temeke',
 283: 'Isevya',
 920: 'Msasani',
 1258: 'Sinza',
 831: 'Miburani',
 180: 'Gerezani',
 216

NameError: name 'trainpred' is not defined

In [48]:
train_destrict

array([ 28, 123,  70, ..., 112,  35,  78], dtype=int8)

In [55]:
trainpred = pd.DataFrame(train_destrict,columns=["ward"])
trainpred = trainpred.replace({"ward": dick})

In [56]:
trainpred.head()

ward
0           Bombo
1        Chiponda
2  Bupandwam'hela
3     Bomba Mbili
4          Bweleo

In [57]:
worked_out.head()

ward         main
0  1131     Nyanguge
1  1110      Nyakato
2  1228      Segerea
3   451  Kijitonyama
4   433    Kigamboni

In [58]:
#worked_out[worked_out["district"] == 28]

In [59]:
test_destrict

array([ 66,   9,  79, ...,   1, 117,  53], dtype=int8)

In [60]:
testpred = pd.DataFrame(test_destrict,columns=["ward"])

In [61]:
testpred = testpred.replace({"ward": dick})

In [62]:
testpred.head()

ward
0     Bungu
1    Bakoba
2   Busolwa
3  Bwongera
4   Bisheke

In [63]:
data.head()

region  district         ward  latitude  longitude
0         Mwanza        53     Nyanguge  -2.36921   33.57654
1         Mwanza        21      Nyakato  -2.53201   32.94780
2  Dar es Salaam        19      Segerea  -6.84188   39.21102
3  Dar es Salaam        38  Kijitonyama  -6.77949   39.24092
4  Dar es Salaam       118    Kigamboni  -6.82792   39.31021

In [ ]:
#trainpred.replace({"district": dick})

In [65]:
d =trainpred.replace({"ward": dick})

In [66]:
t =testpred.replace({"ward": dick})

In [68]:
d.to_csv('wardtrain.csv',index = False)
t.to_csv('wardtest.csv',index = False)